kind: Service
apiVersion: v1
metadata:
  name: identity-manager-service
spec:
  selector:
    app: tm
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31337